# version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_dw
    environment:
      POSTGRES_USER: dbt_user
      POSTGRES_PASSWORD: dbt_password
      POSTGRES_DB: my_warehouse
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.8.0
    container_name: dbt_runner
    volumes:
      - .:/usr/app/dbt  # Mounts your local code into the container
    profiles:
      - dbt_only  # Prevents it from starting automatically with 'up'
    environment:
      DBT_PROFILES_DIR: /usr/app/dbt
    depends_on:
      - db

volumes:
  postgres_data: